### PR TITLE
devtools source maps fix and select2 - select box replacement

### PR DESCRIPTION
**Pull request by ddzieduch**
Require : 

```
npm install
grunt
```

### CODE REVIEW

**Comment by mcnilz** [comment]
there are still some bugs. added some fixes on our internal git

**Comment by ddzieduch** [comment]
Can you marge this to to develop or master? It will be easier to make a contribution with all the necessary changes in one branch.

Do I still have to do something on the branch `test-select2-on-develop`

**Comment by mcnilz** [comment]
I updated and pushed [test-select2-on-develop](https://github.com/webvariants/policat/tree/test-select2-on-develop) branch. I added some fixes for select2 already. But I am not sure if it is 100% compatible with running actions already.

**Comment by mcnilz** [comment]
I created a new pull request from the test-select2-on-develop branch #12 
maybe we can close this pull request

**Pull request closed without merging**
